import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import type { AnalysisResult } from "@/types";

// ============================================================
// POST /api/report
// Body: { data: AnalysisResult, format: "json" | "text" }
// Returns: Formatted report
// ============================================================

const ReportSchema = z.object({
  data: z.record(z.unknown()),
  format: z.enum(["json", "text"]).default("json"),
});

export async function POST(req: NextRequest): Promise<NextResponse> {
  try {
    const body = await req.json();
    const validation = ReportSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { success: false, error: "Invalid report data" },
        { status: 400 }
      );
    }

    const { data, format } = validation.data;
    const result = data as unknown as AnalysisResult;

    if (format === "text") {
      const report = generateTextReport(result);
      return new NextResponse(report, {
        status: 200,
        headers: {
          "Content-Type": "text/plain",
          "Content-Disposition": `attachment; filename="${result.symbol ?? "report"}-investment-report.txt"`,
        },
      });
    }

    // JSON format
    const jsonReport = generateJsonReport(result);
    return new NextResponse(JSON.stringify(jsonReport, null, 2), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="${result.symbol ?? "report"}-investment-report.json"`,
      },
    });
  } catch (error) {
    console.error("Report generation error:", error);
    return NextResponse.json(
      { success: false, error: "Report generation failed" },
      { status: 500 }
    );
  }
}

// ============================================================
// Report Generators
// ============================================================

function generateJsonReport(result: AnalysisResult) {
  return {
    reportMetadata: {
      generatedAt: new Date().toISOString(),
      reportVersion: "1.0",
      dataSource: result.dataSource,
      analyzedAt: result.analyzedAt,
    },
    company: result.company,
    ticker: result.symbol,
    sector: result.sector,
    industry: result.industry,
    ceo: result.ceo,
    headquarters: result.headquarters,
    marketData: {
      currentPrice: result.currentPrice,
      marketCap: result.marketCap,
      pe: result.pe,
      eps: result.eps,
      high52Week: result.high52Week,
      low52Week: result.low52Week,
      change: result.change,
      changePercent: result.changePercent,
    },
    financials: {
      revenue: result.revenue,
      netIncome: result.netIncome,
      grossMargin: result.grossMargin,
      netMargin: result.netMargin,
      roe: result.roe,
      debtToEquity: result.debtToEquity,
      freeCashFlow: result.freeCashFlow,
    },
    scores: {
      financial: result.financialScore,
      business: result.businessScore,
      risk: result.riskScore,
      overall: result.overallScore,
    },
    decision: {
      recommendation: result.decision.toUpperCase(),
      confidence: result.confidence,
      pros: result.pros,
      cons: result.cons,
      summary: result.summary,
      detailedReasoning: result.detailedReasoning,
    },
    swot: result.swot,
  };
}

function generateTextReport(result: AnalysisResult): string {
  const line = "=".repeat(60);
  const divider = "-".repeat(60);

  const formatCurrency = (n: number) => {
    if (!n) return "N/A";
    if (Math.abs(n) >= 1e12) return `$${(n / 1e12).toFixed(2)}T`;
    if (Math.abs(n) >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
    if (Math.abs(n) >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
    return `$${n.toFixed(2)}`;
  };

  return `
${line}
   AI INVESTMENT RESEARCH REPORT
   Generated by InvestIQ - AI Investment Agent
   Date: ${new Date().toLocaleDateString()}
${line}

COMPANY: ${result.company} (${result.symbol})
Exchange: ${result.exchange}  |  Sector: ${result.sector}  |  Industry: ${result.industry}
CEO: ${result.ceo}  |  HQ: ${result.headquarters}
Website: ${result.website}

${divider}
MARKET DATA
${divider}
Current Price:  $${result.currentPrice?.toFixed(2) ?? "N/A"}
Change (Day):   ${result.changePercent >= 0 ? "+" : ""}${result.changePercent?.toFixed(2)}%
Market Cap:     ${formatCurrency(result.marketCap)}
P/E Ratio:      ${result.pe?.toFixed(2) ?? "N/A"}x
EPS:            $${result.eps?.toFixed(2) ?? "N/A"}
52-Week High:   $${result.high52Week?.toFixed(2) ?? "N/A"}
52-Week Low:    $${result.low52Week?.toFixed(2) ?? "N/A"}

${divider}
FINANCIAL SUMMARY
${divider}
Revenue:        ${formatCurrency(result.revenue)}
Net Income:     ${formatCurrency(result.netIncome)}
Gross Margin:   ${result.grossMargin?.toFixed(1)}%
Net Margin:     ${result.netMargin?.toFixed(1)}%
ROE:            ${result.roe?.toFixed(1)}%
Debt/Equity:    ${result.debtToEquity?.toFixed(2)}x
Free Cash Flow: ${formatCurrency(result.freeCashFlow)}

${divider}
AI ANALYSIS SCORES
${divider}
Financial Score:  ${result.financialScore}/100
Business Score:   ${result.businessScore}/100
Risk Score:       ${result.riskScore}/100 (Safety)
OVERALL SCORE:    ${result.overallScore}/100

${divider}
INVESTMENT DECISION
${divider}
Recommendation: *** ${result.decision.toUpperCase()} ***
Confidence:     ${result.confidence}%

PROS:
${result.pros.map((p, i) => `  ${i + 1}. ${p}`).join("\n")}

CONS:
${result.cons.map((c, i) => `  ${i + 1}. ${c}`).join("\n")}

SUMMARY:
${result.summary}

DETAILED REASONING:
${result.detailedReasoning}

${divider}
SWOT ANALYSIS
${divider}
STRENGTHS:
${result.swot.strengths.map((s) => `  + ${s}`).join("\n")}

WEAKNESSES:
${result.swot.weaknesses.map((w) => `  - ${w}`).join("\n")}

OPPORTUNITIES:
${result.swot.opportunities.map((o) => `  > ${o}`).join("\n")}

THREATS:
${result.swot.threats.map((t) => `  ! ${t}`).join("\n")}

${line}
DISCLAIMER: This report is AI-generated for informational purposes only.
It is NOT financial advice. Always consult a qualified financial advisor
before making investment decisions. Past performance does not guarantee
future results.
${line}
Data Sources: ${result.dataSource}
Analyzed At: ${result.analyzedAt}
${line}
`;
}
